services:
  db:
    image: 'postgres:latest'
    env_file:
      '.env'
    ports:
      - '5437:5432'
  
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    env_file:
      '.env'
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  api:
    build: .
    ports:
      - "8081:8081"
    env_file:
      '.env'
    depends_on:
      - db
    
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
